server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos: # 服务注册
      server-addr: 192.168.64.101:8848
    gateway:
      routes:
        - id: consumer-service # 路由标示，必须唯一
          uri: lb://consumer-service # 路由目的地
          predicates: # 断言，判断请求是否符合规则
            - Path=/consumer/** # 路劲断言
        - id: producer-service # 路由标示，必须唯一
          uri: lb://producer-service # 路由目的地 也可以http请求地址
          predicates: # 断言，判断请求是否符合规则
            - Path=/producer/** # 路劲断言


